name: Java CI 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        java: [11, 17, 21]
        distribution: ['temurin']
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
          cache: maven

      - name: Build with Maven
        run: ./mvnw -B clean package javadoc:javadoc --file pom.xml
